import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import { Toaster } from "react-hot-toast";
import ReactQueryProvider from "@/lib/ReactQueryProvider";
import WhatsAppButton from "@/components/special/whatsUp/WhatsAppButton";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <Toaster
            position="top-left"
            reverseOrder={false}
            toastOptions={{
              duration: 4000,
              style: {
                fontFamily: "inherit",
                marginButton: "30px",
                zIndex: "999999999999",
              },
            }}
          />
          <WhatsAppButton />

          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
